apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nhutq/angocd-basic:f2a8d65db2483bf50130c72a5bb61ceab0cea10e
          imagePullPolicy: Always   # Important
          ports:
            - containerPort: 80