apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nhutq/angocd-basic:afa8ce072e3aafafb52de41ebced621ad4c2718a
          imagePullPolicy: Always   # Important
          ports:
            - containerPort: 80