apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nhutq/angocd-basic:a91be93fd828421619a51c3ca8065d8fcbebcbc1
          imagePullPolicy: Always   # Important
          ports:
            - containerPort: 80