apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: nginx-updater
  namespace: argocd
spec:
  imageList:
    - name: nginx
      image: tqnhu4/angocd-basic
      updateStrategy: latest

  writeBackMethod: git

  git:
    repoURL: https://github.com/tqnhu4/argocd-basic.git
    branch: main