apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gitops
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=tqnhu4/angocd-basic
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/tqnhu4/argocd-basic.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true